---
dist: trusty
sudo: false

language: minimal

script:
  - docker-compose up --build -d
  - docker cp ./goss.yml missioncontrol:/goss.yml
  # install goss
  - docker exec -i missioncontrol bash -lc 'curl -fsSL https://goss.rocks/install | sh'
  # wait for coredns to start
  - docker exec -i missioncontrol bash -lc 'while ! pgrep coredns >/dev/null ; do sleep 5 ; done'
  # execute goss tests
  - docker exec -i missioncontrol goss --gossfile /goss.yml validate

notifications:
  email:
    on_success: never
    on_failure: never
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
